sudo: false
dist: trusty

# blocklist
branches:
  except:
  - /^release.*/

# safelist
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+\.\d+$/
  
language: java
jdk:
  - oraclejdk8

before_install:
  - gradle wrapper

script:
  - travis_wait 30 ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
    provider: releases
    api_key: $GIT_REPO_TOKEN
    file_glob: true
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
      all_branches: true

